# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190215_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
